trigger:
- main

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '97b6b140-3d3f-4842-8da9-ab0fa8888bd0'
  imageRepository: 'calcguruapp'
  containerRegistry: 'calcguru.azurecr.io'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        # Add your build steps here, such as compiling code, running tests, etc.
        # Remove the Docker task that builds and pushes the Docker image
      displayName: 'Run Build Steps'
